name = "Avaritian_space_board_game"
uuid = "84dab3df-53e1-4310-bd83-3200e028cd62"
authors = ["AliceRoselia <63040919+AliceRoselia@users.noreply.github.com>"]
version = "0.1.0"

[deps]
FunctionWrappers = "069b7b12-0de2-55c6-9aab-29f3d0a68a2e"
